/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sorting.h"

bool_t
xdr_Array(register XDR *xdrs, Array *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE(xdrs, (2 + (MAXSIZE)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->num, MAXSIZE,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->size))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->time1))
				return (FALSE);
		} else {
#if defined(_LP64) || defined(_KERNEL)
			{
				register int *genp;

				for (i = 0, genp = objp->num;
					i < MAXSIZE; i++) {
					IXDR_PUT_INT32(buf, *genp++);
				}
			}
			IXDR_PUT_INT32(buf, objp->size);
			IXDR_PUT_INT32(buf, objp->time1);
#else
			{
				register int *genp;

				for (i = 0, genp = objp->num;
					i < MAXSIZE; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->size);
			IXDR_PUT_LONG(buf, objp->time1);
#endif
		}
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE(xdrs, (2 + (MAXSIZE)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->num, MAXSIZE,
				sizeof (int), (xdrproc_t) xdr_int))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->size))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->time1))
				return (FALSE);
		} else {
#if defined(_LP64) || defined(_KERNEL)
			{
				register int *genp;

				for (i = 0, genp = objp->num;
					i < MAXSIZE; i++) {
					*genp++ = IXDR_GET_INT32(buf);
				}
			}
			objp->size = IXDR_GET_INT32(buf);
			objp->time1 = IXDR_GET_INT32(buf);
#else
			{
				register int *genp;

				for (i = 0, genp = objp->num;
					i < MAXSIZE; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->size = IXDR_GET_LONG(buf);
			objp->time1 = IXDR_GET_LONG(buf);
#endif
		}
		return (TRUE);
	}

	if (!xdr_vector(xdrs, (char *)objp->num, MAXSIZE,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->size))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->time1))
		return (FALSE);
	return (TRUE);
}
